# Generated by Django 3.0.5 on 2021-04-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Wallet name')),
                ('currency', models.CharField(choices=[('rub', 'rub'), ('usd', 'usd'), ('eur', ' eur')], max_length=3)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(max_length=200, verbose_name='Value')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Description')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.Wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(max_length=200, verbose_name='Value')),
                ('converted_value', models.FloatField(blank=True, max_length=200, null=True, verbose_name='Converted value')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_taken', to='api.Wallet', verbose_name='Recipient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_sent', to='api.Wallet', verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Exchange',
                'verbose_name_plural': 'Exchanges',
                'ordering': ['date'],
            },
        ),
    ]
