# Generated by Django 3.0.5 on 2021-04-16 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken', to='api.Wallet', verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='api.Wallet', verbose_name='Sender'),
        ),
    ]
