# Generated by Django 3.0.5 on 2021-04-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210401_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='wallet name'),
        ),
    ]
