# Generated by Django 3.0.5 on 2021-04-16 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210416_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.FloatField(max_length=200, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('rub', 'rub'), ('usd', 'usd'), ('eur', ' eur')], max_length=3),
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(max_length=200, verbose_name='Value')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_taken', to='api.Wallet', verbose_name='Recipient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_sent', to='api.Wallet', verbose_name='Sender')),
            ],
        ),
    ]
