# Generated by Django 3.0.5 on 2021-04-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
    ]
